// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDeJKtUz_rkdMj5qxiXYm6eZvhMPPIOyhI',
    appId: '1:167905644119:web:6a20280d975ab7d6d3dd12',
    messagingSenderId: '167905644119',
    projectId: 'auth-examapp',
    authDomain: 'auth-examapp.firebaseapp.com',
    storageBucket: 'auth-examapp.appspot.com',
    measurementId: 'G-5KMNS39X9F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBLj8yKJt_FCsK4Opax-0O3VxFWh_GERtU',
    appId: '1:167905644119:android:57dcc003e9219e98d3dd12',
    messagingSenderId: '167905644119',
    projectId: 'auth-examapp',
    storageBucket: 'auth-examapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC3KW6e2ooOEdWZ_znknXN2bYtCSuBfvA4',
    appId: '1:167905644119:ios:1810e20977e1643dd3dd12',
    messagingSenderId: '167905644119',
    projectId: 'auth-examapp',
    storageBucket: 'auth-examapp.appspot.com',
    iosBundleId: 'com.example.authExamappp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC3KW6e2ooOEdWZ_znknXN2bYtCSuBfvA4',
    appId: '1:167905644119:ios:1810e20977e1643dd3dd12',
    messagingSenderId: '167905644119',
    projectId: 'auth-examapp',
    storageBucket: 'auth-examapp.appspot.com',
    iosBundleId: 'com.example.authExamappp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDeJKtUz_rkdMj5qxiXYm6eZvhMPPIOyhI',
    appId: '1:167905644119:web:b7d7e4014a5154fcd3dd12',
    messagingSenderId: '167905644119',
    projectId: 'auth-examapp',
    authDomain: 'auth-examapp.firebaseapp.com',
    storageBucket: 'auth-examapp.appspot.com',
    measurementId: 'G-1EQBC266F5',
  );
}
